# service:
#   - context: Academic
#    roles:
#      - start: 2017
#        end: present
#        title: "Study counseling GIScience"
#        entity: Project LIFE Healthy Forest

service:

  - context: Academic
    roles:
      - start: 2017
        end: present
        title: "Study counseling GIScience"
        entitiy: "Institute of Geography, Department of GIScience"

  - context: Consultancy
    roles:
    - start: 2015
      end: present
      role: "GfK Geomarketing"


  - context: Guest Editor
    roles:
    - role: "Plos One"

  - context: Journal Reviewer
    roles:
      - role: Applied Vegetation Science
      - role: Ecological Modelling
      - role: Erdkunde
      - role: Forests
      - role: Natural Hazards
      - role: Plos One
      - role: Sensors
      - role: Sustainability
