# service:
#   - context: Academic
#    roles:
#      - start: 2017
#        end: present
#        title: "Study counseling GIScience"
#        entity: Project LIFE Healthy Forest

service:

  - context: Academic
    roles:
      - start: 2017
        end: present
        title: "Study advisor for the M.Sc. program in GIScience"
        entitiy: "Institute of Geography, Department of GIScience"
      - start: 2017
        end: 2017
        title: "Co-Organizer of the MSCJ LIFE Spring School on the statistical analysis of hyperspectral and high-dimensional remote sensing data"

  - context: Consultancy
    roles:
    - start: 2015
      end: present
      role: "GfK Geomarketing"


  - context: Guest Editor
    roles:
    - role: Plos One ({\color{ImperialLightBlue}\href{https://doi.org/10.1371/journal.pone.0190572}{https://doi.org/10.1371/journal.pone.0190572}})

  - context: Journal Reviewer
    roles:
      - role: Applied Vegetation Science
      - role: Ecological Modelling
      - role: Erdkunde
      - role: Forests
      - role: Natural Hazards
      - role: Plos One
      - role: Sensors
      - role: Sustainability
